### ISSUE TITLE
webaccessibility.guide is not viewable in lynx

### ISSUE THREAD

**Issue by larryhynes** [fejes713/accessibility-guide#9]
HI

[lynx](https://lynx.invisible-island.net/), the text browser commonly used to render the web by the visually impaired (and used by lots of other folks), does not seem to render your website at [https://webaccessibility.guide/](https://webaccessibility.guide/). It looks to me like this is caused by the site being rendered by some sort of javascript? (lynx does not support js.) Is it possible to include some (accessible) html on your site as a fallback?

**Comment by NothingEverHappens** [comment]
This also looks like a great tip :)

**Comment by fejes713** [comment]
Hey, @larryhynes thanks for addressing this issue. Right now the website is generated with [hyperapp](https://github.com/jorgebucaran/hyperapp) on the frontend. I am not sure if `hyperapp` has any way of SSR.

Do you have any other ideas on how to achieve this? Maybe a fallback `html` page saying that you need JS in order to access the website's content?

**Comment by larryhynes** [comment]
Maybe change way the website is made? It's up to you. If it was up to me, I would make sure the site is accessible using a standard tool used by the impaired. (You might, some day, also check how your site renders in [edbrowse](http://edbrowse.org/) which was written by a blind developer and is another tool used to access the web by those who cannot avail of the usual means. It can handle js.)

**Comment by atomiks** [comment]
@fejes713 check `@hyperapp/render`. I use a naive prerendering technique in my hyperapp-kit repo

**Comment by fejes713** [comment]
Legend is back 🎉 thanks @atomiks will check it out.
